import { View, Text, ScrollView, Image } from 'react-native'
import React from 'react'
import { SafeAreaView } from 'react-native-safe-area-context'
import { moderateScale, verticalScale } from 'react-native-size-matters'
import ArticleView from '@/components/ArticleView'
import SubContent from '@/components/SubContent'

const solidWasteDisposal = () => {
  return (
    <SafeAreaView className='flex-1 px-5 gap-y-3' style={{paddingTop: verticalScale(20)}}>
      <View className='mb-5'>
        <Text className='font-pbold text-secondary' style={{fontSize: moderateScale(26)}}>Types of Solid Waste Disposal</Text>
        <Text className='font-pregular' style={{fontSize: moderateScale(14)}}>from testbook.com</Text>
      </View>
      <ScrollView bounces={false} showsVerticalScrollIndicator={false}>
        <View className='mb-5'>
            <Image source={require('../../assets/images/articles/type-disposal.jpg')} style={{height: verticalScale(150), width: '100%'}} resizeMode='cover'/>
        </View>
        <Text className='font-pregular text-justify mb-5' style={{fontSize: moderateScale(16)}}>
            Effective solid waste disposal and management are essential for minimizing environmental impact and promoting sustainability. 
            A range of methods is employed to manage and mitigate the effects of waste generated by human activities. 
            These methods include both traditional and modern approaches, each contributing to the efficient handling and reduction of waste.
        </Text>
        <ArticleView title='Solid Waste Disposal Methods and Management' 
            description='Solid waste disposal and management involve various techniques to handle and process waste materials, aiming to minimize environmental impact and support sustainable practices. Key methods include:'
        />
        <SubContent title='Landfilling:' desc='Waste is deposited and compacted in engineered sites, then covered with soil to manage odors, prevent disease spread, and reduce environmental contamination. 
            Landfills must adhere to design and regulatory standards to protect soil, groundwater, and air quality.'
        />
        <SubContent title='Incineration:' desc='This process involves the controlled burning of waste at high temperatures, which reduces waste volume and generates energy. 
            Effective air pollution control systems are necessary to limit harmful emissions.'
        />
        <SubContent title='Recycling:' 
            desc='Recycling separates, processes, and reuses materials such as paper, plastics, glass, and metals. This method decreases the demand for raw materials, conserves energy, and reduces greenhouse gas emissions.'
        />
        <SubContent title='Composting' 
            desc='This method involves the biological decomposition of organic waste to produce nutrient-rich compost used in agriculture and landscaping. Composting reduces landfill volume and diverts organic waste from the waste stream.'
        />
        <SubContent title='Waste-to-Energy'
            desc='This approach converts waste into energy through methods like anaerobic digestion or incineration, generating heat or electricity and reducing reliance on fossil fuels while minimizing waste volume.'
        />
        <SubContent title='Hazardous Waste Treatment'
            desc='Hazardous waste requires specialized treatment to neutralize, detoxify, or remove harmful components before disposal, protecting both human health and the environment.'
        />
        <SubContent title='Source Reduction' 
            desc='This strategy aims to reduce waste production at the source through measures such as redesigning products, substituting materials, and promoting reuse and repair. 
            Source reduction helps conserve resources and decrease waste disposal needs.'
        />
        <SubContent title='Biogas Generation:'
            desc='This method involves a process where organic waste decomposes in the absence of oxygen to produce methane gas, which can be used for energy, and nutrient-rich material that can be used as fertilizer.' 
        />
      </ScrollView>
    </SafeAreaView>
  )
}

export default solidWasteDisposal