import { View, Text, ScrollView } from 'react-native'
import React from 'react'
import { SafeAreaView } from 'react-native-safe-area-context'
import CustomParagraph from './CustomParagraph'
import { moderateScale, verticalScale } from 'react-native-size-matters'
import CustomText from './CustomText'
import Icon from 'react-native-remix-icon'

const privacyPolicy = () => {
  return (
    <SafeAreaView className='px-5' style={{paddingTop: verticalScale(20)}}>
      <View className='bg-white'>
        <View className='border-b-[1px] border-gray-400 flex-row items-center py-3'>
            <Icon name='arrow-left-s-line' color='black' size={28} className='mr-3'/>
            <Text className='font-psemibold text-primary' style={{fontSize: moderateScale(16)}}>Privacy Policy</Text>
        </View>
        <View className='h-screen py-5 px-3'>
            <ScrollView bounces={false} showsVerticalScrollIndicator={false}>
                <View className='mb-5'>
                    <View className='gap-y-7 mb-5'>
                        <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>Privacy Policy</Text>
                        <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>Last updated: April 22, 2024</Text>
                        <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>This Privacy Policy describes Our policies and procedures on the collection, 
                            use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        </Text>
                        <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>We use Your Personal data to provide and improve the Service. 
                            By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. 
                            This Privacy Policy has been created with the help of the Privacy Policy Generator.
                        </Text>
                    </View>
                    <View>
                        <Text className='font-pbold mb-3' style={{fontSize: moderateScale(20)}}>Interpretation and Definition</Text>
                        <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Interpretation</Text>
                        <CustomParagraph text='The words of which the initial letter is capitalized have meanings defined under the following conditions. 
                            The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.'
                        />
                    </View>
                    <View>
                        <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Definitions</Text>
                        <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>For the purpose of this Privacy Policy:</Text>
                        <CustomText bold='Account' light='means a unique account created for You to access our Service pr parts of our Service'/>
                        <CustomParagraph text='Affiliate means an entity that controls, is controlled by or is under common control with a party, 
                            where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.'
                        />
                        <CustomText bold={'Application'} light={'refers to WasteRedux, the software program provided by the Company.'}/>
                        <CustomText bold={'Company'} light={'(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to WasteRedux.'}/>
                        <CustomText bold={'Country'} light={'refers to : Philippines'}/>
                        <CustomText bold={'Device'} light={'means any device that can access the Service such as a computer, a cellphone or a digital tablet.'}/>
                        <CustomText bold={'Personal Data'} light={'is any information that relates to an identified or identifiable individual.'}/>
                        <CustomText bold={'Service'} light={'refers to the Application.'}/>
                        <CustomText bold={'Service Provider'} 
                            light={'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.'}
                        />
                        <CustomText bold={'Usage Data'} light={'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).'}/>
                        <CustomText bold={'You'} light={'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'}/>
                    </View>
                    <View className='mb-7'> 
                        <Text className='font-pbold' style={{fontSize: moderateScale(20)}}>Collecting and Using Your Personal Data</Text>
                        <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>Types of Data Collected</Text>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Personal Data</Text>
                            <CustomParagraph text='While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:'/>
                            <CustomParagraph text='Email address'/>
                            <CustomParagraph text='First name and last name'/>
                            <CustomParagraph text='Usage Data'/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Usage Data</Text>
                            <CustomParagraph text='Usage Data is collected automatically when using the service.'/>
                            <CustomParagraph text="Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data."/>
                            <CustomParagraph text='When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, 
                                the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.'
                            />
                            <CustomParagraph text='We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.'/>
                            <CustomParagraph text='Information Collected while Using the Application'/>
                            <CustomParagraph text='While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:' />
                            <CustomParagraph text="·        Pictures and other information from your Device's camera and photo library" />
                            <CustomParagraph text="We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device."/>
                            <CustomParagraph text="You can enable or disable access to this information at any time, through Your Device settings."/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Use of Your Personal Data</Text>
                            <CustomParagraph text='The Company may use Personal Data for the following purposes:'/>
                            <CustomParagraph text="To provide and maintain our Service, including to monitor the usage of our Service."/>
                            <CustomParagraph text="To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user."/>
                            <CustomParagraph text='For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.' />
                            <CustomParagraph text="To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, 
                                products or contracted services, including the security updates, when necessary or reasonable for their implementation."
                            />
                            <CustomParagraph text='To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.'/>
                            <CustomParagraph text='To manage Your requests: To attend and manage Your requests to Us.' />
                            <CustomParagraph text='For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, 
                                liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.'
                            />
                            <CustomParagraph text='For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.'/>
                            <CustomParagraph text='We may share Your personal information in the following situations:'/>
                            <CustomParagraph text='·        With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.'/>
                            <CustomParagraph text='·        For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.'/>
                            <CustomParagraph text='·        With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.'/>
                            <CustomParagraph text='·        With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.'/>
                            <CustomParagraph text='·        With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.'/>
                            <CustomParagraph text='·        With Your consent: We may disclose Your personal information for any other purpose with Your consent.'/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Retention of Your Personal Data</Text>
                            <CustomParagraph text='The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.'/>
                            <CustomParagraph text='The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.'/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Transfer of Your Personal Data</Text>
                            <CustomParagraph text="Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction."/>
                            <CustomParagraph text='Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.'/>
                            <CustomParagraph text='The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.'/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Delete Your Personal Data</Text>
                            <CustomParagraph text='You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.'/>
                            <CustomParagraph text='Our Service may give You the ability to delete certain information about You from within the Service.'/>
                            <CustomParagraph text='You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.'/>
                            <CustomParagraph text='Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.'/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Disclosure of Your Personal Data</Text>
                            <CustomParagraph text='Business Transactions'/>
                            <CustomParagraph text='If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.'/>
                            <CustomParagraph text='Law enforcement'/>
                            <CustomParagraph text='Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).'/>
                            <CustomParagraph text='Other legal requirements'/>
                            <CustomParagraph text='The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:'/>
                            <CustomParagraph text='·        Comply with a legal obligation'/>
                            <CustomParagraph text='·        Protect and defend the rights or property of the Company'/>
                            <CustomParagraph text='·        Prevent or investigate possible wrongdoing in connection with the Service'/>
                            <CustomParagraph text='·        Protect the personal safety of Users of the Service or the public'/>
                            <CustomParagraph text='·        Protect against legal liability'/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Security of Your Personal Data</Text>
                            <CustomParagraph text='The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. 
                                While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.'
                            />
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Children's Privacy</Text>
                            <CustomParagraph text='Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. 
                                If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. 
                                If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.'
                            />
                            <CustomParagraph text="If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."/>
                        </View>
                        <View>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Link to Other Websites</Text>
                            <CustomParagraph text="Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit."/>
                            <CustomParagraph text='We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.'/>
                            <CustomParagraph text='Changes to this Privacy Policy'/>
                            <CustomParagraph text='We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.'/>
                            <CustomParagraph text='We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.'/>
                            <CustomParagraph text='You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.'/>
                        </View>
                        <View className=''>
                            <Text className='font-pbold' style={{fontSize: moderateScale(15)}}>Contact Us</Text>
                            <CustomParagraph text='If you have any questions about this Privacy Policy, You can contact us:'/>
                            <Text className='font-pregular' style={{fontSize: moderateScale(15)}}>By email: <Text className='text-primary font-pbold'> wastereduxoffice@gmail.com</Text></Text>
                        </View>
                        
                    </View>
                </View>
            </ScrollView>
        </View>
      </View>
    </SafeAreaView>
  )
}

export default privacyPolicy